import type { NextPage } from 'next'
import Head from 'next/head'
import * as Icon from "../components/icons"

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-screen flex justify-center items-center">
                <div className="flex flex-col gap-4">
                    <span className="text-7xl font-bold text-zinc-600">
                        <span className="text-lime-700 opacity-90 hover:opacity-100 ease-in duration-300">enerji</span>
                        <span className="text-sky-700 opacity-90 hover:opacity-100 ease-in duration-300">.dev</span>
                    </span>
                    <div className="flex gap-2 justify-center items-center">
                        <a className="text-zinc-700" href="https://discord.gg/WG7YtsRFRp">
                            <Icon.Discord size={40} />
                        </a>
                        <a className="text-zinc-700" href="https://twitter.com/enerjidev">
                            <Icon.Twitter size={35} />
                        </a>
                        <a className="text-zinc-700" href="https://github.com/enerjidev">
                            <Icon.Github size={35} />
                        </a>
                        <a className="text-zinc-700" href="https://instagram.com/enerjidev">
                            <Icon.Instagram size={34} />
                        </a>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Home
